services:
  cruise-finder:
    build: .
    container_name: cruise-finder
    restart: unless-stopped
    ports:
      - "8502:8501"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"